[project]
name = "fastword"
version = "0.1.0"
description = "A secure local password manager with PyQt6"
authors = [{name = "Nolan Coe"}]
dependencies = [
    "PyQt6",
    "cryptography"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
